.TH SENTIMENT_SENTINEL 1 "2024/7/26" "Sentiment Sentinel Manual"

.SH NAME
sentiment_sentinel \- Predict sentiment based on a message.

.SH SYNOPSIS
sentiment_sentinel [options]

.SH DESCRIPTION
The sentiment_sentinel program uses the naive bayes algorithm to predict the sentiment of a given message or messages.

.SH OPTIONS
.TP
\-h, --help
Displays the help menu.
.TP
\--version
Displays the version number.
.TP
\-n message
Enter the message for the algorithm to predict the sentiment of.

.SH EXAMPLES
.B
cat ./test.txt | sentiment_sentinel

.B
sentiment_sentinel -m "I love baked potatoes!" -s .5

.SH EXIT STATUS
0 for success; 1 for error.

.SH AUTHOR
Written by Badger Code.